postgres:
  outputs:
    prod:
        type: postgres
        threads: 4
        host: "{{ env_var('POSTGRES_HOST') }}"
        port: 5432
        user: "{{ env_var('POSTGRES_USER') }}"
        pass: "{{ env_var('POSTGRES_PASSWORD') }}"
        dbname: "{{ env_var('POSTGRES_DB') }}"
        schema: prd

  target: prod